### ISSUE TITLE
Important modifications to be applied to Workshop 10

### ISSUE THREAD

**Issue by katherinehebert** [QCBSRworkshops/workshop10#9]
Before developing and modifying this workshop, please read through the [presenter and developer protocol](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#guidelines) **carefully** and refer back to it regularly as you work.

### Specific to adapting workshops to a remote framework:

- [x] **Fit this workshop to a 3-hour format**. The duration of this workshop should be ~3 hours (including exercises and one or two breaks of 5 minutes; excluding longer breaks). To fit this format, please add, edit, or **hide** slides from existing workshops. You can begin by hiding repetitive examples, non-essential slides, or some of the additional advanced slides that are included at the end of some workshops. Some workshops will be more difficult to shorten than others, due to their subject matter. It is not a problem to let these workshops run slightly over 3 hours to guarantee accurate and complete information. (Use your judgment). DO NOT delete slides. Use the `instruction: hidden_remote` tag. See an example below:

```
---
exclude: true

# Slide title: I love statistics!

### Content: Amazing!
---
```
- [x] **Develop new or adapt current exercises to better suit the remote workshop format and the use of breakout rooms**. Exercises should be informative and engaging. Remember to leave time for students to work through exercises and ask questions. Refer to [these guidelines](https://qcbsrworkshops.github.io/presenter-developer-protocol/_book/developing-en.html#active-learning) to find suggestions of exercises promoting active learning. You may use additional resources to create the exercises.

### Specific to slide structure, grammar and style

- [x] **Ensure code is working correctly and that code matches workshop presentation**. Continue to check this as you make changes.

- [x] **Proofread correcting spelling, grammar, or punctuation errors (for example, )**.

- [x] **Look for and correct the content of slides that overflow the screen (for example, slides 56, 61, 69, 70, 75, 95)**.

- [x] **Look for and correct prose that mentions function names, object names, package names and code chunks that do not use backticks**.

- [x] **Look for and correct unnecessary abbreviations (e.g. use do not instead of don’t).**

- [x] **Correct unnecessary long sentences**.

- [x] **Ensure that the slides are written in a consistent style, which helps with the flow of workshops and student understanding**. This is especially important when working collaboratively with other developers.

- [x] **Include presenter notes to the slides you modify**. You can write notes for yourself to read in the presenter mode (press the keyboard shortcut `p`). These notes are written under three question marks `???`. See the example below:

```
---
The content of this workshop is essential for your graduate studies.

???

Note: _The presenter should sing this slide to the participants_.
---
```
### Specific to the translation of this workshop

- [x] **Add and translate the new modified content to the French version of the workshop**.

- [x] **Proofread and correct spelling, grammar and punctuation errors**.

- [x] **Correct unnecessary long sentences**.

### Specific to this workshop

- [x] Resolve issue #2 
- [ ] Resolve issue #3 
- [x] Resolve issue #5 
- [x] Remove content related to the package `MVPARTwrap` because it is difficult to install is not essential (see issue #6 )
- [ ] Try to add a challenge to resolve issue #1 
- [ ] more to come...

**Comment by katherinehebert** [comment]
We excluded all slides about the multivariate regression trees to cut the workshop content enough for a 3 hour limit. These slides were therefore not addressed during this development round, with the exception of removing content about `MVPARTwrap`.

**Comment by estebangongora** [comment]
We have moved any remaining issues on this list to a new issue list for the 2021-2022 workshop series (#15)

**Comment by estebangongora** [comment]
We have moved any remaining issues on this list to a new issue list for the 2021-2022 workshop series (#15)
